spring.application.name=Spring-AI-RAG-PDF

# Ollama 設定：
spring.ai.ollama.base-url=http://localhost:11434
# 用於聊天回答問題的模型
spring.ai.ollama.chat.model=llama3.1:8b
# 用於 RAG 的搜尋階段(把文字轉向量的模型)
spring.ai.ollama.embedding.options.model=llama3.1:8b

# 向量庫設定（使用 SimpleVectorStore）：
spring.ai.vectorstore.simple.initialize-schema=always

# 允許 Bean 覆蓋（教學環境方便實驗）：
spring.main.allow-bean-definition-overriding=true
